#cloud-config

# Cloud-init config file for provisioning VMs with Docker+Rocker Rv4.1.2
# for Max's paper.
#
# Code author: Russell A. Edson, Biometry Hub
# Date last modified: 02/03/2022

# Update repos and upgrade to latest (Ubuntu 20.04 LTS)
# FIXME: This causes an apt race condition, apparently?
#repo_update: true
#repo_upgrade: all

# Installing Docker using the convenience script, pulling in files
# from git and setting up Rocker container for Rv4.1.2 and all
# ancillary libraries
# FIXME: Seem to get apt race condition on cloud-init, so (for now)
#        just wait 30 seconds or so until it's finished.
runcmd:
 - [ sh, -c, "sleep 30" ]
 - [ sh, -c, "apt update && apt -y upgrade && apt install -y curl git" ]
 - [ curl, -fsSL, "https://get.docker.com", -o, get-docker.sh ]
 - [ sh, ./get-docker.sh ]
 - [ runuser, -l, ubuntu, -c, "cd ~ && git clone https://github.com/biometryhub/tmle-phacking" ]
 - [ docker, build, -t, "tmle-phacking", "/home/ubuntu/tmle-phacking" ]
